appname: "Testapp"

charset: "UTF-8"

logger: "console"
log_level: "debug"
warnings: 1

engines:
    template_toolkit:
        ENCODING: utf8
        DEFAULT: 'no.tt'

views: '../../views'

plugins:
  DBIC:
    default:
      dsn: dbi:SQLite:dbname=test.sqlite
      schema_class: TestDB

Strehler:
    admin_secured: 1
    languages: ['it', 'en']
    default_language: 'it'
    timezone: 'Europe/Rome'

